### ISSUE TITLE
Use urllib3 library packaged with Requests

### ISSUE THREAD

**Issue by dylan171** [ChannelFinder/pyCFClient#13]
If I understand correctly, Requests comes packaged with a version of urllib3, so you don't need the extra dependency.

This is giving my problems when using pyCFClient with Anaconda. The Anaconda repository contains a version of the Requests library, but it does not have a version of the urllib3 library.

The only use of urllib3 I could find is [here](https://github.com/ChannelFinder/pyCFClient/blob/89f5639335aa7ebcb910289e1f74089857180d62/channelfinder/ChannelFinderClient.py#L14)

So, I have just replaced that line with:

`from requests.packages.urllib3.poolmanager import PoolManager`

I can provide a pull request if that would help.

**Comment by shroffk** [comment]
Hi Dylan,
I think this was added when we were experiencing issues with warnings from urllib which needed to be suppressed...but as you point out it does not seemed to be used anywhere, so we should clean up the imports.
