### ISSUE TITLE
client spec v2.0

### ISSUE THREAD

**Issue by shroffk** [ChannelFinder/pyCFClient#2]
Support more python like interface. Change the methods to return lists and dictonaries instead of Channel, Tag, Property Objects

**Comment by shengb** [comment]
Does it mean that the new one will support multiple value support for one property and tag?

**Comment by shroffk** [comment]
shengb:
This has to be added to the service
In the meanwhile you could use something like follows
device:['corrector','HorizontalCorrector']

**Comment by shroffk** [comment]
tag = {“name”: “tagName”, “owner”:”tagOwner”}
property = {“name”: “propName”, “value”: “propValue”, “owner”:”tagOwner”}
