### ISSUE TITLE
Error in documentation for find methed

### ISSUE THREAD

**Issue by dylan171** [ChannelFinder/pyCFClient#20]
@archman was using the CF client and found that the doc string for the find method is [incorrect](https://github.com/ChannelFinder/pyCFClient/blob/master/channelfinder/ChannelFinderClient.py#L239)
```
For multiValued searches
>>> find(name='pattern1,pattern2')
will return all the channels which match either pattern1 OR pattern2
```
However we found that the name patterns were applied as pattern1 AND pattern2, which appears consistent with the CF API reference.

In this case I think the CF client documentation is in error, @shroffk can you please confirm?

**Comment by shroffk** [comment]
Hello,
Ok you are right I think this is a documentation error,

find (name='pattern1,pattern2') return s AND'd
while
find(name='pattern1|pattern2') returns OR'd

**Comment by archman** [comment]
@shroffk Correct, thanks!
